import { writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import $RefParser from '@apidevtools/json-schema-ref-parser'
import { jsonSchemaToZod } from 'json-schema-to-zod'

const __dirname = dirname(fileURLToPath(import.meta.url))
const generatedDir = resolve(__dirname, '../src/generated')

const STAC_VERSION = '1.0.0'
const BASE_URL = `https://raw.githubusercontent.com/radiantearth/stac-spec/v${STAC_VERSION}`

const schemas = [
  {
    name: 'item',
    url: `${BASE_URL}/item-spec/json-schema/item.json`,
    exportName: 'itemSchema',
  },
  {
    name: 'collection',
    url: `${BASE_URL}/collection-spec/json-schema/collection.json`,
    exportName: 'collectionSchema',
  },
  {
    name: 'catalog',
    url: `${BASE_URL}/catalog-spec/json-schema/catalog.json`,
    exportName: 'catalogSchema',
  },
]

mkdirSync(generatedDir, { recursive: true })

for (const schema of schemas) {
  console.log(`Fetching ${schema.name} schema...`)
  const derefed = await $RefParser.dereference(schema.url)

  console.log(`Converting ${schema.name} to Zod...`)
  const code = jsonSchemaToZod(derefed as object, {
    name: schema.exportName,
    module: 'esm',
    zodVersion: 3,
  })

  const output = [
    `// Generated by scripts/update-schemas.ts — do not edit manually`,
    `// Source: STAC spec v${STAC_VERSION} — ${schema.url}`,
    code,
  ].join('\n')

  const outPath = resolve(generatedDir, `${schema.name}.ts`)
  writeFileSync(outPath, output)
  console.log(`Wrote ${outPath}`)
}

console.log('Done.')
